### ISSUE TITLE
cfreate custom role in questionnare

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/ts-models#2]
1. create custom role in questionare 
2. uncomment this line https://github.com/EscolaLMS/ts-models/blob/main/config/typescript.php#L111

**Comment by KrzysztofDziedziechEscolasoft** [comment]
https://github.com/EscolaLMS/Questionnaire/commit/509ff0e772f5960280d1985de92f2693c7d9bc74

**Comment by KrzysztofDziedziechEscolasoft** [comment]
you mean custom rule in this task
